# Generated by Django 2.2.6 on 2019-12-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='detail',
            field=models.TextField(default=''),
        ),
    ]
