# Generated by Django 2.2.6 on 2019-11-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetime',
            name='lectureroom',
            field=models.CharField(default='default', max_length=8),
        ),
    ]
