# Generated by Django 2.2.5 on 2019-11-06 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timetable_main',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_main', to='assaapp.Timetable'),
        ),
    ]
