# Generated by Django 2.2.6 on 2019-12-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='academic_year',
            field=models.CharField(max_length=8),
        ),
    ]
