# Generated by Django 2.2.6 on 2019-12-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit_max',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='user',
            name='credit_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='days_per_week',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='user',
            name='major_max',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='user',
            name='major_min',
            field=models.IntegerField(default=0),
        ),
    ]
