# Generated by Django 2.2.6 on 2019-12-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assaapp', '0002_auto_20191204_1955'),
        ('assaapp', '0002_building_detail'),
    ]

    operations = [
    ]
