# Generated by Django 2.2.5 on 2019-10-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assaapp', '0002_auto_20191031_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='semester',
            field=models.CharField(default='', max_length=8),
        ),
    ]
