# Generated by Django 2.2.6 on 2019-11-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assaapp', '0002_building'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='x',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='y',
            new_name='longitude',
        ),
    ]
