# Generated by Django 2.2.6 on 2019-11-22 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assaapp', '0003_auto_20191114_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='courses',
        ),
        migrations.AddField(
            model_name='customcourse',
            name='title',
            field=models.CharField(default='default', max_length=128),
        ),
        migrations.CreateModel(
            name='CustomCourseTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(default=0)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assaapp.CustomCourse')),
            ],
        ),
    ]
