# Generated by Django 2.2.5 on 2019-10-30 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assaapp', '0003_auto_20191030_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#FFFFFF', max_length=8)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assaapp.Course')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assaapp.Timetable')),
            ],
        ),
        migrations.RenameModel(
            old_name='Course_Time',
            new_name='CourseTime',
        ),
        migrations.DeleteModel(
            name='Timetable_Course',
        ),
    ]
