# Generated by Django 2.2.6 on 2019-12-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assaapp', '0003_merge_20191207_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='detail',
        ),
        migrations.AddField(
            model_name='customcoursetime',
            name='detail',
            field=models.TextField(default=''),
        ),
    ]
