# Generated by Django 2.2.6 on 2019-12-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assaapp', '0004_auto_20191207_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='repre_name',
            field=models.CharField(default='default', max_length=16),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(default='default', max_length=64),
        ),
    ]
