# Generated by Django 2.2.6 on 2019-12-12 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assaapp', '0003_user_last_recommend_page'),
        ('assaapp', '0005_auto_20191208_0858'),
    ]

    operations = [
    ]
