# Generated by Django 2.2.6 on 2019-12-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assaapp', '0006_merge_20191212_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(max_length=32),
        ),
    ]
