# Generated by Django 2.2.6 on 2019-12-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assaapp', '0006_merge_20191212_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recommend_base_timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', related_name='base', to='assaapp.Timetable'),
        ),
    ]
