# Generated by Django 2.2.6 on 2019-12-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assaapp', '0007_auto_20191213_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.IntegerField(default=2018),
        ),
    ]
