# Generated by Django 2.2.6 on 2019-12-13 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assaapp', '0007_auto_20191213_0432'),
        ('assaapp', '0007_user_recommend_base_timetable'),
    ]

    operations = [
    ]
