# Generated by Django 2.2.6 on 2019-12-13 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assaapp', '0008_merge_20191213_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recommend_base_timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base', to='assaapp.Timetable'),
        ),
    ]
