# Generated by Django 2.2.6 on 2019-12-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assaapp', '0009_auto_20191213_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='recommend_base_timetable',
        ),
    ]
