# Generated by Django 2.2.7 on 2019-12-14 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assaapp', '0008_auto_20191214_0246'),
        ('assaapp', '0010_remove_user_recommend_base_timetable'),
    ]

    operations = [
    ]
