# Generated by Django 2.2.8 on 2019-12-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assaapp', '0011_merge_20191214_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='repre_name',
            field=models.CharField(default='default', max_length=32),
        ),
    ]
