export const GET_AUTH = 'GET_AUTH';
export const GET_USER = 'GET_USER';
export const GET_FRIEND = 'GET_FRIEND';
export const SET_SEND_STATUS = 'SET_SEND_STATUS';

export const GET_USER_SEARCH = 'GET_USER_SEARCH';
export const RECEIVE_FRIEND = 'RECEIVE_FRIEND';
export const DELETE_FRIEND = 'DELETE_FRIEND';
export const REJECT_FRIEND = 'REJECT_FRIEND';
export const CANCEL_FRIEND = 'CANCEL_FRIEND';


export const GET_TIMETABLES = 'GET_TIMETABLES';
export const GET_TIMETABLE = 'GET_TIMETABLE';
export const GET_TIMETABLE_FRIEND = 'GET_TIMETABLE_FRIEND';
export const GET_COURSES = 'GET_COURSES';
export const EDIT_TIMETABLE = 'EDIT_TIMETABLE';
export const POST_COURSE = 'POST_COURSE';
export const POST_TIMETABLE = 'POST_TIMETABLE';
export const POST_MAIN_TIMETABLE = 'POST_MAIN_TIMETABLE';
export const POST_CUSTOM_COURSE = 'POST_CUSTOM_COURSE';

export const DELETE_COURSE = 'DELETE_COURSE';
export const DELETE_TIMETABLE = 'DELETE_TIMETABLE';

export const GET_COURSE_SCORE = 'GET_COURSE_SCORE';