export const GET_AUTH = 'GET_AUTH';
export const GET_USER = 'GET_USER';
export const GET_FRIEND = 'GET_FRIEND';
export const SET_SEND_STATUS = 'SET_SEND_STATUS';
export const GET_USER_SEARCH = 'GET_USER_SEARCH';

export const SEND_FRIEND_UNDO = 'SEND_REQUEST_FRIEND_UNDO';
export const RECEIVE_FRIEND = 'RECIEVE_REQUEST_FRIEND';
export const RECEIVE_FRIEND_UNDO = 'RECIEVE_REQUEST_FRIEND_UNDO';
export const DELETE_FRIEND = 'DELETE_FRIEND';
