export const GET_AUTH = 'GET_AUTH';
export const GET_USER = 'GET_USER';
export const GET_FRIEND = 'GET_FRIEND';
export const SET_SEND_STATUS = 'SET_SEND_STATUS';

export const GET_USER_SEARCH = 'GET_USER_SEARCH';
export const RECEIVE_FRIEND = 'RECEIVE_FRIEND';
export const DELETE_FRIEND = 'DELETE_FRIEND';
export const REJECT_FRIEND = 'REJECT_FRIEND';
export const CANCEL_FRIEND = 'CANCEL_FRIEND';


export const GET_TIMETABLES = 'GET_TIMETABLES';
export const GET_TIMETABLE = 'GET_TIMETABLE';
export const GET_TIMETABLE_FRIEND = 'GET_TIMETABLE_FRIEND';
export const GET_COURSES = 'GET_COURSES';
export const RESET_COURSE = 'RESET_COURSE';
export const EDIT_TIMETABLE = 'EDIT_TIMETABLE';
export const POST_COURSE = 'POST_COURSE';
export const POST_TIMETABLE = 'POST_TIMETABLE';
export const POST_MAIN_TIMETABLE = 'POST_MAIN_TIMETABLE';
export const POST_CUSTOM_COURSE = 'POST_CUSTOM_COURSE';

export const DELETE_COURSE = 'DELETE_COURSE';
export const DELETE_TIMETABLE = 'DELETE_TIMETABLE';

export const GET_RATED_COURSE = 'GET_RATED_COURSE';
export const GET_UNRATED_COURSE = 'GET_UNRATED_COURSE';
export const GET_EXCEPT_COURSE = 'GET_EXCEPT_COURSE';
export const RESET_COURSE_SCORE = 'RESET_COURSE_SCORE';
export const PUT_COURSEPREF = 'PUT_COURSEPREF';
export const PUT_COURSEPREF_TEMP = 'PUT_COURSEPREF_TEMP';
