# Generated by Django 2.2.6 on 2019-12-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timepref',
            name='score',
            field=models.IntegerField(default=3),
        ),
    ]
