# Generated by Django 2.2.6 on 2019-12-11 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assaapp', '0002_auto_20191204_1955'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommend', '0002_auto_20191205_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='default', max_length=8)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assaapp.Course')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.RecommendTimetable')),
            ],
        ),
    ]
